# Generated by Django 5.2.4 on 2025-07-26 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('IDOperacao', models.AutoField(primary_key=True, serialize=False)),
                ('Parametros', models.CharField()),
                ('Resultado', models.CharField()),
                ('DtInclusao', models.DateField(auto_now_add=True)),
                ('IDUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastro.usuario')),
            ],
            options={
                'db_table': 'Operacao',
            },
        ),
    ]
