# Generated by Django 5.2.4 on 2025-07-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IDUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField()),
                ('Email', models.CharField()),
                ('Senha', models.CharField()),
                ('DtInclusao', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
